FROM python:3.7-buster

COPY integration_tests/assets/bin /usr/local/bin
COPY . /tmp/xivo

WORKDIR /tmp/xivo
RUN true && \
    pip install -r requirements.txt kombu && \
    python setup.py install && \
    true

CMD ["myservice.py"]
