FROM python:3.7-buster

COPY integration_tests/assets/bin /usr/local/bin
COPY . /tmp/xivo

WORKDIR /tmp/xivo

# importlib_metadata<5.0.0  # from kombu - https://github.com/celery/kombu/issues/1600
RUN true && \
    pip install -r requirements.txt kombu 'importlib_metadata<5.0.0' && \
    python setup.py install && \
    true

CMD ["myservice.py"]
