FROM python:2.7.16-buster

COPY integration_tests/assets/bin /usr/local/bin
COPY . /tmp/xivo

RUN cd /tmp/xivo && pip install -r requirements.txt kombu

RUN cd /tmp/xivo && python setup.py install

CMD ["myservice.py"]
