from python:2.7.13

COPY integration_tests/assets/bin /usr/local/bin
COPY . /tmp/xivo

RUN pip install \
    kombu \
    flask \
    https://github.com/wazo-pbx/xivo-bus/archive/master.zip \
    python-consul==0.7.0 \
    netifaces

RUN cd /tmp/xivo && python setup.py install

CMD ["myservice.py"]
